---
title: "EDLD652 Lab 3"
author: 
  - "Rachael Latimer"
  - "Hyeonjin Cha"
  - "Tess Sameshima"
date: "2/6/2021"
output: html_document
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, message = FALSE)
#install.packages("gghighlight")
library(tidyverse)
library(here)
library(rio)
library(knitr)
library(janitor)
library(patchwork)
library(ggplot2)
library(forcats)
library(lubridate)
library(gghighlight)
library(ggtext)
#library(colorblindr)
library(colorBlindness)
```

```{r data}
#loading data
hprod <- import(here("data", "honeyproduction.csv")) %>% 
  clean_names() %>% 
  as_tibble()

hprod2 <- hprod %>% 
  mutate(production=totalprod/10000)

```

## R Markdown



## Draft Plots
```{r plot1}

#plot1 alternative

plot1b <- ggplot(hprod2, aes(year, production)) + 
  geom_line(aes(group=state),color="grey") + 
  geom_line(data = hprod2 %>% 
            filter(state == "CA"| state == "OR"|state == "WA"), 
            aes(color=state),size=1) + 
  labs(title = "Total Honey Production by State, from 1998 to 2012",
       subtitle = "Highlighting the West Coast",
       x = "Year",
       y = "Honey Production (in 10,000lbs)") +
  theme_minimal()
plot1b
```

```{r plot2}
colorBlindness::cvdPlot(plot1b)
```

```{r plot3}
plot1b + scale_color_viridis_d()
```

```{r plot4}
#Download the file here denoting the region and division of each state.
stregdiv <- import(here("data", "state_reg_div.xlsx")) %>% 
  clean_names() %>% 
  as_tibble()

#Join the file with your honey file.
p4_data <- hprod %>% 
  left_join(stregdiv, by = c("state" = "state_code")) %>% 
  rename(state_code = state, state = state.y)

p4_data %>% 
  group_by(state) %>% 
  summarize(avghoney= mean(totalprod))

p4_data %>% 
  summarize(avghoney= mean(totalprod))

#plot without highlights
p4_data %>% 
  group_by(state_code, region) %>% 
  summarize(avghoney= mean(totalprod)) %>%
  ggplot(aes(fct_reorder(state_code, avghoney), avghoney/1000)) + 
  geom_col(aes(fill=region)) + 
  coord_flip() + 
  theme_minimal() + 
  labs(title = "Average Honey Production by State, from 1998 to 2012",
       subtitle = "Highliting above-average performing states",
       x = "State",
       y = "Average Honey Production (in 1,000lbs)",
       fill = "Region")

#plot with highlights
p4_data %>% 
  group_by(state_code, region) %>% 
  summarize(avghoney= mean(totalprod)) %>%
  ggplot(aes(fct_reorder(state_code, avghoney), avghoney/1000)) + 
  geom_col(aes(fill=region)) + 
  coord_flip() + 
  gghighlight(avghoney > 4169086) + #average honey production across all state and year
  theme_minimal() + 
  labs(title = "Average Honey Production by State, from 1998 to 2012",
       subtitle = "Highliting above-average performing states",
       x = "State",
       y = "Average Honey Production (in 1,000lbs)",
       fill = "Region")

#gghighlight show that no state from Northeast produced above average amount of honey during the period!
```



```{r plot5}
#load region dataframe
reg_div <- import(here("data", "state_reg_div.xlsx"))

hprodregion <- hprod

hprodregion <- hprodregion %>%   
  rename("State Code" = "state") %>% 
    left_join(reg_div, by = "State Code")
    

#join dfs by statecode aggregate
plot_5 <- hprodregion %>% 
  aggregate(totalprod~Region + year, data = ., mean) %>% 
    ggplot(aes(year, fct_reorder(Region,totalprod))) +
      geom_tile(aes(fill = totalprod)) +
      coord_fixed() +
      scale_fill_distiller("Average Honey Production \nin lb",palette = "Blues", na.value = "black") +
      labs(title = "Average Honey Production Across Years by Region",
      x = "Year",
      y = "Region")  +
  theme(legend.title = element_text(size = 10))
      
plot_5
```

```{r plot6}
#colorblind package
#devtools::install_github("wilkelab/cowplot")
#install.packages("colorspace", repos = "http://R-Forge.R-project.org")
#devtools::install_github("clauswilke/colorblindr")

#install.packages("albersusa")
#remotes::install_github("hrbrmstr/albersusa")
library(albersusa)

#map data
us <- usa_sf() %>% 
  rename("State Code" = "iso_3166_2") %>%
   left_join(hprodregion, by = "State Code")

#plot value of hones by states acorss years
plot_6<- ggplot(us) +
  geom_sf(aes(fill = totalprod)) +
    facet_wrap(~year) +
    theme_void() +
    scale_fill_distiller(palette = "Blues",
                         name = "Honey Production \n(lb)",
                         na.value = "black") +
    labs(title = "Honey Produced per State Across Years")
plot_6


```



